### ISSUE TITLE
license texts missing from published crates since refactoring into workspace

### ISSUE THREAD

**Issue by decathorpe** [bash/term-color#29]
It looks like this was missed in this commit: https://github.com/bash/terminal-colorsaurus/commit/1ef15a5e65377166e38b9e7cc15620b97956d7f0

To include license texts in published crates, you will need to add symbolic links (or copies) to the license texts at the project root.

**Comment by bash** [comment]
Shoot! New release coming shortly 🏃🏼

**Comment by decathorpe** [comment]
Can confirm, thank you for the quick fix!
